// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restino.Persistence;

#nullable disable

namespace Restino.Persistence.Migrations
{
    [DbContext(typeof(RestinoDbContext))]
    [Migration("20250112113549_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restino.Domain.Entities.Accommodations", b =>
                {
                    b.Property<Guid>("AccommodationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHotProposition")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("AccommodationsId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            AccommodationsId = new Guid("47fc830b-751c-4b54-88e3-3281d746f3fd"),
                            Address = "123 Beachside Ave, Miami, FL",
                            Capacity = 4,
                            CategoryId = new Guid("c119661c-1d5a-42c1-8819-6b0885af4d4a"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Cozy apartments with a sea view and modern amenities.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/397741258.jpg?k=225b07468ede098c5df3b7037eaa6b681dd01f94d392a0bb96827f4467515fdd&o=&hp=1",
                            IsHotProposition = false,
                            Name = "Sunrise Apartments",
                            Price = 12000
                        },
                        new
                        {
                            AccommodationsId = new Guid("9db960f8-38e7-4fb4-8db5-6c82f65a654c"),
                            Address = "98 Main Blvd, Chicago, IL",
                            Capacity = 3,
                            CategoryId = new Guid("c119661c-1d5a-42c1-8819-6b0885af4d4a"),
                            CreatedDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Stylish apartment with a stunning view of the city skyline.",
                            ImgUrl = "https://images.stockcake.com/public/8/8/1/8814dc5c-08e3-48f6-be0a-287e67513bf8_large/city-view-apartment-stockcake.jpg",
                            IsHotProposition = false,
                            Name = "City View Apartment",
                            Price = 22000
                        },
                        new
                        {
                            AccommodationsId = new Guid("6b7e2693-aa97-4f54-97cc-8cc3bdd5d130"),
                            Address = "303 Sky Tower, Los Angeles, CA",
                            Capacity = 5,
                            CategoryId = new Guid("c119661c-1d5a-42c1-8819-6b0885af4d4a"),
                            CreatedDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Luxury penthouse with a private rooftop terrace.",
                            ImgUrl = "https://ikosresorts.com/wp-content/uploads/2024/03/IKOS-ANDALUSIA-DELUXE-2-BEDROOM-PENTHOUSE-SUITE-SEA-VIEW_Living-Room_2880x1745-scaled.jpg",
                            IsHotProposition = true,
                            Name = "Penthouse Suite",
                            Price = 50000
                        },
                        new
                        {
                            AccommodationsId = new Guid("b3b8f3d5-9efe-497a-9454-d2d16965cfa0"),
                            Address = "121 Oak Street, Dallas, TX",
                            Capacity = 6,
                            CategoryId = new Guid("c119661c-1d5a-42c1-8819-6b0885af4d4a"),
                            CreatedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Cozy and spacious apartment in a quiet suburban area.",
                            ImgUrl = "https://cooganslandscape.com/wp-content/uploads/2018/05/cs_suburban-retreat_02.jpg",
                            IsHotProposition = false,
                            Name = "Suburban Retreat",
                            Price = 18000
                        },
                        new
                        {
                            AccommodationsId = new Guid("ff38ccf6-d319-40d1-8869-c7ae8a415f5e"),
                            Address = "45 Palm Street, Beverly Hills, CA",
                            Capacity = 8,
                            CategoryId = new Guid("8f67819c-0d09-43e8-b64f-17c9123b6040"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Spacious villa with a private pool and garden.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/166987475.jpg?k=8dc75e9a7e77e2c381d8dd40607a11cc139063f9fa83cb290b0780ea0d36b134&o=&hp=1",
                            IsHotProposition = true,
                            Name = "Luxury Villa",
                            Price = 75000
                        },
                        new
                        {
                            AccommodationsId = new Guid("e3132a60-2e38-4366-b0ac-59d653e3400f"),
                            Address = "22 Hilltop Ave, Aspen, CO",
                            Capacity = 7,
                            CategoryId = new Guid("8f67819c-0d09-43e8-b64f-17c9123b6040"),
                            CreatedDate = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "A serene villa with panoramic mountain views.",
                            ImgUrl = "https://i.pinimg.com/736x/e6/70/75/e6707559c50325571f27b7b7854f0812.jpg",
                            IsHotProposition = false,
                            Name = "Mountain Villa",
                            Price = 55000
                        },
                        new
                        {
                            AccommodationsId = new Guid("826dace9-c0ba-40b2-bd92-41f9d6519a08"),
                            Address = "15 Ocean Blvd, Malibu, CA",
                            Capacity = 6,
                            CategoryId = new Guid("8f67819c-0d09-43e8-b64f-17c9123b6040"),
                            CreatedDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Elegant beachfront villa with stunning ocean views.",
                            ImgUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoTwfzqd1cqiVQ160798aa9akDS16tqx3WiA&s",
                            IsHotProposition = true,
                            Name = "Beachfront Villa",
                            Price = 75000
                        },
                        new
                        {
                            AccommodationsId = new Guid("e7136862-7c13-4a57-a05f-e09b9ae98d06"),
                            Address = "30 Green Lane, San Francisco, CA",
                            Capacity = 5,
                            CategoryId = new Guid("8f67819c-0d09-43e8-b64f-17c9123b6040"),
                            CreatedDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Charming villa with a beautiful private garden.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/126789518.jpg?k=408ac13d6f98710a36962e3eef601f42f8bb889fc06f3c37ed5aed2c0ac1668b&o=&hp=1",
                            IsHotProposition = false,
                            Name = "Garden Villa",
                            Price = 50000
                        },
                        new
                        {
                            AccommodationsId = new Guid("eac0f796-b80d-43ff-800e-dfbe0a5dbb60"),
                            Address = "89 Alpine Road, Aspen, CO",
                            Capacity = 6,
                            CategoryId = new Guid("418ade5f-d0b7-4545-b9de-beafbefffa66"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Charming chalet located near the ski slopes.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/341395058.jpg?k=8feed4d0fbeb5e5d5c21a6738a5e196e7020a91156ac49a4b858ffa2f28296bb&o=&hp=1",
                            IsHotProposition = true,
                            Name = "Mountain Chalet",
                            Price = 30000
                        },
                        new
                        {
                            AccommodationsId = new Guid("97b5de46-c8fa-42ff-b752-e1baaf09a844"),
                            Address = "8 Pine Hill Rd, Lake Tahoe, CA",
                            Capacity = 5,
                            CategoryId = new Guid("418ade5f-d0b7-4545-b9de-beafbefffa66"),
                            CreatedDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Chalet by the lake with beautiful forest surroundings.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/344315015.jpg?k=b521cb84b76ad6348350e4547963a6191c7a7a9758384ba5dea2ee1c270ea0b8&o=&hp=1",
                            IsHotProposition = false,
                            Name = "Lakeside Chalet",
                            Price = 35000
                        },
                        new
                        {
                            AccommodationsId = new Guid("90bea0a5-4dc5-4461-a6ca-ec2633ce4acf"),
                            Address = "25 Forest Road, Whistler, BC",
                            Capacity = 4,
                            CategoryId = new Guid("418ade5f-d0b7-4545-b9de-beafbefffa66"),
                            CreatedDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Rustic chalet nestled in the forest, offering a peaceful retreat.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/166571658.jpg?k=f650daa2d249b002682dddd40bb83a47c1c534e03b7b48b579aa81d3c9735fec&o=&hp=1",
                            IsHotProposition = true,
                            Name = "Forest Chalet",
                            Price = 37500
                        },
                        new
                        {
                            AccommodationsId = new Guid("cdd387fe-0834-494b-9a63-2a622375d36c"),
                            Address = "30 Snowy Peak Ave, Zermatt, CH",
                            Capacity = 8,
                            CategoryId = new Guid("418ade5f-d0b7-4545-b9de-beafbefffa66"),
                            CreatedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Perfect for skiing enthusiasts, this chalet is located near top ski resorts.",
                            ImgUrl = "https://myhome.at/wp-content/uploads/2021/12/ian-keefe-OgcJIKRnRC8-unsplash-scaled-e1657608875630-830x514.jpg",
                            IsHotProposition = false,
                            Name = "Winter Chalet",
                            Price = 50000
                        },
                        new
                        {
                            AccommodationsId = new Guid("dcbbfc78-9191-4ced-97c6-da3c51b1adae"),
                            Address = "12 Countryside Lane, Vermont, VT",
                            Capacity = 5,
                            CategoryId = new Guid("cf0976f2-83c1-4708-afea-3e4785db6d66"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Peaceful cottage surrounded by nature.",
                            ImgUrl = "https://img.freepik.com/premium-photo/portrayal-peaceful-cottage-surrounded-by-nature-using-warm-comforting-colors_181667-39977.jpg",
                            IsHotProposition = true,
                            Name = "Cozy Cottage",
                            Price = 18000
                        },
                        new
                        {
                            AccommodationsId = new Guid("48f6d005-6237-465c-a413-e2924e9773e8"),
                            Address = "14 Pinewood Rd, Asheville, NC",
                            Capacity = 4,
                            CategoryId = new Guid("cf0976f2-83c1-4708-afea-3e4785db6d66"),
                            CreatedDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Charming cottage surrounded by lush greenery and trees.",
                            ImgUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUacp1F7dYO4ZMtPX5Uy5omf2y1_Tz-mjV9Q&s",
                            IsHotProposition = false,
                            Name = "Forest Cottage",
                            Price = 16000
                        },
                        new
                        {
                            AccommodationsId = new Guid("70adcfec-32f1-4ae7-a67a-a1690c5ffaa9"),
                            Address = "22 Riverbank Dr, Jackson, WY",
                            Capacity = 6,
                            CategoryId = new Guid("cf0976f2-83c1-4708-afea-3e4785db6d66"),
                            CreatedDate = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "A beautiful cottage next to a peaceful river.",
                            ImgUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREH3Bw3qjBoMHcGu989hceIjNCNTn0GRGcuA&s",
                            IsHotProposition = true,
                            Name = "Riverside Cottage",
                            Price = 21000
                        },
                        new
                        {
                            AccommodationsId = new Guid("0ff2a035-d55d-422c-a7c0-6a3eb4a2b51a"),
                            Address = "5 Ocean View St, Cape Cod, MA",
                            Capacity = 4,
                            CategoryId = new Guid("cf0976f2-83c1-4708-afea-3e4785db6d66"),
                            CreatedDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Cozy seaside cottage perfect for a relaxing getaway.",
                            ImgUrl = "https://media.istockphoto.com/id/539151605/photo/village.jpg?s=612x612&w=0&k=20&c=i1956HGGH6KL_p8uZehqHSInxNzwV9BwYTmoc8lHqC4=",
                            IsHotProposition = false,
                            Name = "Seaside Cottage",
                            Price = 1900
                        },
                        new
                        {
                            AccommodationsId = new Guid("9ebd806d-08e7-40d6-9dc8-408c590c119d"),
                            Address = "77 Desert Oasis, Joshua Tree, CA",
                            Capacity = 2,
                            CategoryId = new Guid("d1e68fb1-9cd9-4018-9ba5-cfb9bd315b0d"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Luxury glamping experience under the stars.",
                            ImgUrl = "https://images.squarespace-cdn.com/content/v1/65a12f7fd4021742aad7a454/f0a80575-93a1-4ffd-9c1c-e09cdac449d0/unnamed.jpg",
                            IsHotProposition = false,
                            Name = "Glamping Paradise",
                            Price = 2000
                        },
                        new
                        {
                            AccommodationsId = new Guid("f0aefde0-bc3d-4cfc-b477-00b3ddec847c"),
                            Address = "9 Forest Trail, Oregon, OR",
                            Capacity = 4,
                            CategoryId = new Guid("d1e68fb1-9cd9-4018-9ba5-cfb9bd315b0d"),
                            CreatedDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Comfortable tent in the middle of a serene forest.",
                            ImgUrl = "https://hipcamp-res.cloudinary.com/images/c_limit,f_auto,h_1200,q_60,w_1920/v1623141528/campground-photos/ppury203ptsjwa3xaori/a-tent-in-the-forest-tent-in-the-forest-kin-kin-qld-sunshine-coast-glamping-canvas-tent-bell-tent.jpg",
                            IsHotProposition = false,
                            Name = "Forest Tent",
                            Price = 2200
                        },
                        new
                        {
                            AccommodationsId = new Guid("965155a6-8b18-45e9-9a60-b92b7876fa69"),
                            Address = "19 Hilltop Rd, Colorado, CO",
                            Capacity = 3,
                            CategoryId = new Guid("d1e68fb1-9cd9-4018-9ba5-cfb9bd315b0d"),
                            CreatedDate = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Glamping site with breathtaking mountain views.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/268933268.jpg?k=31035bb853f6356e1edab72d633e887d0dc18f24bb18d45ff7392a8f95c21431&o=&hp=1",
                            IsHotProposition = true,
                            Name = "Mountain Glamping",
                            Price = 2800
                        },
                        new
                        {
                            AccommodationsId = new Guid("9015220b-2e8d-4067-a5cb-9a556260e1da"),
                            Address = "10 Beachfront Ave, Florida, FL",
                            Capacity = 2,
                            CategoryId = new Guid("d1e68fb1-9cd9-4018-9ba5-cfb9bd315b0d"),
                            CreatedDate = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Exclusive glamping experience by the beach.",
                            ImgUrl = "https://epicexcursionsnc.com/wp-content/uploads/sites/5139/2021/12/Ultimate-Island-Glamping-Experience-image-1.jpg?resize=360%2C240&zoom=2",
                            IsHotProposition = false,
                            Name = "Beach Glamping",
                            Price = 2400
                        },
                        new
                        {
                            AccommodationsId = new Guid("4cbafdc3-446b-4ab3-bf2c-2c0b3c744492"),
                            Address = "25 Backpacker Lane, Prague, CZ",
                            Capacity = 12,
                            CategoryId = new Guid("9fbd8bb8-1a85-4305-87fd-4b3d011b1a5a"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Affordable hostel for travelers with a social vibe.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/215321123.jpg?k=424cc4139871d8c2b6ca4f825afcc94002327662e8268afce3776159d0e241a0&o=&hp=1",
                            IsHotProposition = true,
                            Name = "Budget Hostel",
                            Price = 4000
                        },
                        new
                        {
                            AccommodationsId = new Guid("3abf0f37-8079-4900-bd6b-8679585a5607"),
                            Address = "8 Urban Street, Berlin, DE",
                            Capacity = 10,
                            CategoryId = new Guid("9fbd8bb8-1a85-4305-87fd-4b3d011b1a5a"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Convenient city hostel with easy access to tourist attractions.",
                            ImgUrl = "https://lviv-city-hostel.nochi.com.ua/data/Photos/OriginalPhoto/2478/247894/247894309/Lviv-City-Hostel-Room.JPEG",
                            IsHotProposition = false,
                            Name = "City Hostel",
                            Price = 3500
                        },
                        new
                        {
                            AccommodationsId = new Guid("cf0e7c96-b60b-4c6b-8374-57f827fa17a4"),
                            Address = "18 Mountain View Road, Sydney, AU",
                            Capacity = 8,
                            CategoryId = new Guid("9fbd8bb8-1a85-4305-87fd-4b3d011b1a5a"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Simple yet cozy hostel for budget travelers.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/158775758.jpg?k=31bb0155b48892515927e82f2434205cb82299eae53f10723a8b398da8640aec&o=&hp=1",
                            IsHotProposition = true,
                            Name = "Cozy Backpacker Hostel",
                            Price = 4500
                        },
                        new
                        {
                            AccommodationsId = new Guid("c119661c-1d5a-42c1-8819-6b0885af4d4a"),
                            Address = "2 Ocean Blvd, Lisbon, PT",
                            Capacity = 15,
                            CategoryId = new Guid("9fbd8bb8-1a85-4305-87fd-4b3d011b1a5a"),
                            CreatedDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Hostel right by the beach for travelers seeking relaxation.",
                            ImgUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmNzZYaVh2l68QWrmsNggJQS1GxxMPO3Iltw&s",
                            IsHotProposition = false,
                            Name = "Beachfront Hostel",
                            Price = 5000
                        },
                        new
                        {
                            AccommodationsId = new Guid("400c5bff-99c3-4493-a618-6653241bc6b5"),
                            Address = "9 Ocean View Road, Cape Cod, MA",
                            Capacity = 4,
                            CategoryId = new Guid("6f80d6e0-54b3-495d-847b-16a092c8b626"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Enjoy camping with a view of the ocean.",
                            ImgUrl = "https://cf.bstatic.com/xdata/images/hotel/max1024x768/76334100.jpg?k=d369e33cd367722733e61bf38b20ba1fee537abc9b696747ca0e6ae57dc02964&o=&hp=1",
                            IsHotProposition = true,
                            Name = "Seaside Camping",
                            Price = 6000
                        },
                        new
                        {
                            AccommodationsId = new Guid("a4e54b1f-3149-4d9b-8d88-e8b4a174a619"),
                            Address = "20 Alpine Trail, Colorado, CO",
                            Capacity = 6,
                            CategoryId = new Guid("6f80d6e0-54b3-495d-847b-16a092c8b626"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Camp amidst towering mountains for a true outdoor experience.",
                            ImgUrl = "https://images.stockcake.com/public/5/c/c/5ccc3dc0-5051-4b2f-bfed-5a9633c5bc67_large/starry-mountain-camping-stockcake.jpg",
                            IsHotProposition = false,
                            Name = "Mountain Campsite",
                            Price = 5500
                        },
                        new
                        {
                            AccommodationsId = new Guid("1a491f3d-94ac-4df8-a244-0ef6c4a5c5b2"),
                            Address = "12 Forest Rd, Oregon, OR",
                            Capacity = 8,
                            CategoryId = new Guid("6f80d6e0-54b3-495d-847b-16a092c8b626"),
                            CreatedDate = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Secluded campsite in the heart of the forest.",
                            ImgUrl = "https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/205670362.jpg?k=228d9c931b9f22eb9d7dd1127fc4be9086f3e28e4fce5c4a19ce85c40cc0df1c&o=?s=375x210&ar=16x9",
                            IsHotProposition = true,
                            Name = "Forest Camp",
                            Price = 5000
                        },
                        new
                        {
                            AccommodationsId = new Guid("a4ab6df6-66b8-46f7-8198-c94332964006"),
                            Address = "15 Sand Dune Rd, Nevada, NV",
                            Capacity = 5,
                            CategoryId = new Guid("6f80d6e0-54b3-495d-847b-16a092c8b626"),
                            CreatedDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "An adventurous camping experience in the desert.",
                            ImgUrl = "https://www.hostelworld.com/blog/wp-content/uploads/2023/04/parker-hilton-VtGLcivTXtk-unsplash.jpg",
                            IsHotProposition = false,
                            Name = "Desert Camping",
                            Price = 4500
                        });
                });

            modelBuilder.Entity("Restino.Domain.Entities.Categories", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriesId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoriesId = new Guid("c119661c-1d5a-42c1-8819-6b0885af4d4a"),
                            CategoryName = "Appartaments",
                            Description = "Apartments are a modern type of accommodation that combines the comfort of a home with high-quality service. They are ideal for short-term or long-term stays, offering a fully equipped kitchen, spacious interiors, and modern amenities. Apartments are often located in city centers, providing easy access to popular locations. Choosing apartments ensures independence and comfort for travelers who value coziness and the convenience of a private space.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2016/11/30/08/48/bedroom-1872196_1280.jpg"
                        },
                        new
                        {
                            CategoriesId = new Guid("8f67819c-0d09-43e8-b64f-17c9123b6040"),
                            CategoryName = "Villa",
                            Description = "A villa is a luxurious house typically situated in a picturesque area. It is perfect for large groups or families. Villas come equipped with spacious rooms, terraces, swimming pools, and sometimes even gardens. This type of accommodation is designed for those seeking privacy, comfort, and natural beauty. It’s an excellent choice for hosting parties or enjoying a peaceful retreat away from the hustle and bustle of the city.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2013/10/12/18/05/villa-194671_1280.jpg"
                        },
                        new
                        {
                            CategoriesId = new Guid("418ade5f-d0b7-4545-b9de-beafbefffa66"),
                            CategoryName = "Chalet",
                            Description = "A chalet is a traditional mountain house made of wood with a warm and cozy interior. They are most commonly found in mountainous regions and are popular among winter sports enthusiasts. Chalets are ideal for family vacations or romantic getaways. The ambiance of these homes promotes complete relaxation, while fireplaces add a touch of coziness on cold winter evenings.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2019/12/11/12/00/mountain-4688203_1280.jpg"
                        },
                        new
                        {
                            CategoriesId = new Guid("cf0976f2-83c1-4708-afea-3e4785db6d66"),
                            CategoryName = "Cottage",
                            Description = "A cottage is a small country house offering peace and coziness away from the city noise. It usually features a traditional design with modern amenities. Cottages are perfect for family vacations or short getaways into nature. They are often located near forests or lakes, creating ideal conditions for outdoor activities.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2015/08/25/14/16/small-wooden-house-906912_1280.jpg"
                        },
                        new
                        {
                            CategoriesId = new Guid("d1e68fb1-9cd9-4018-9ba5-cfb9bd315b0d"),
                            CategoryName = "Glamping",
                            Description = "Glamping is a combination of luxury and closeness to nature. This type of accommodation offers tents or wooden cabins with all modern conveniences. Glamping provides an authentic outdoor experience without sacrificing comfort. It is perfect for those who love nature but prefer a more luxurious stay.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2021/07/25/06/26/glamping-6490987_1280.jpg"
                        },
                        new
                        {
                            CategoriesId = new Guid("9fbd8bb8-1a85-4305-87fd-4b3d011b1a5a"),
                            CategoryName = "Hostel",
                            Description = "A hostel is a budget-friendly accommodation option for travelers. Typically, it features shared rooms with individual beds, although private rooms are also available. Hostels are ideal for young people and those looking to meet fellow travelers. They often include shared kitchens, common areas, and are usually located in city centers.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2013/06/30/19/07/bed-142516_1280.jpg"
                        },
                        new
                        {
                            CategoriesId = new Guid("6f80d6e0-54b3-495d-847b-16a092c8b626"),
                            CategoryName = "Camping",
                            Description = "Camping is a way to spend time in nature by staying in tents or trailers. It’s a great opportunity to escape civilization, enjoying quiet mornings and starry nights. Campsites are often located near forests, rivers, or mountains, providing opportunities for active leisure such as fishing, hiking, or cycling.",
                            ImgUrl = "https://cdn.pixabay.com/photo/2017/08/17/08/08/camp-2650359_1280.jpg"
                        });
                });

            modelBuilder.Entity("Restino.Domain.Entities.Orders", b =>
                {
                    b.Property<Guid>("OrdersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderPrice")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdersId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Restino.Domain.Entities.Accommodations", b =>
                {
                    b.HasOne("Restino.Domain.Entities.Categories", "Category")
                        .WithMany("Accommodations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Restino.Domain.Entities.Categories", b =>
                {
                    b.Navigation("Accommodations");
                });
#pragma warning restore 612, 618
        }
    }
}
